"""Fixed spelling of accountType to account_type

Revision ID: 0e9e7856eeda
Revises: 85916c70ccdf
Create Date: 2019-12-31 09:08:57.423980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9e7856eeda'
down_revision = '85916c70ccdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_account_type'), 'user', ['account_type'], unique=False)
    op.drop_index('ix_user_accountType', table_name='user')
    op.drop_column('user', 'accountType')
    op.drop_column('user', 'isRoot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isRoot', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('accountType', sa.INTEGER(), nullable=True))
    op.create_index('ix_user_accountType', 'user', ['accountType'], unique=False)
    op.drop_index(op.f('ix_user_account_type'), table_name='user')
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###
