"""Added isRoot boolean field to user

Revision ID: 85916c70ccdf
Revises: 6d2185d40eb2
Create Date: 2019-12-30 19:48:26.909031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85916c70ccdf'
down_revision = '6d2185d40eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isRoot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isRoot')
    # ### end Alembic commands ###
